reverting changes.

diff --git a/.github/workflows/spineapp_sanity.yaml b/.github/workflows/spineapp_sanity.yaml
--- a/.github/workflows/spineapp_sanity.yaml
+++ b/.github/workflows/spineapp_sanity.yaml
@@ -47,42 +47,6 @@ jobs:
       uses: actions/setup-python@v5
       with:
         python-version: '3.10'
-    
-    - name: Log in to GitHub Container Registry
-      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #3.4.0
-      with:
-        registry: ghcr.io
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
-    - name: Sanity Test 
-      run: | 
-       sudo apt-get update
-          
-       lspci | grep -i vga
-       sudo apt install -y python3-nose libxml2-utils vlc
-        
-       python3 -m venv venv
-       source venv/bin/activate
-       pip install --upgrade pip
-       pip install robotframework selenium
-
-       cd edge-ai-suites-repo/manufacturing-ai-suite/industrial-edge-insights-vision/tests/robot_files
-       robot test.robot || true  &
-       sleep 480
-       docker logs dlstreamer-pipeline-server >> dlsps_logs.txt &
-       wait
-       mkdir -p /tmp/test_results
-       cp -r report.html log.html output.xml dlsps_logs.txt /tmp/test_results/
-       passed=$(xmllint --xpath "//return/status[@status='PASS']" ./output.xml | wc -l) || true
-       failed=$(xmllint --xpath "//return/status[@status='FAIL']" ./output.xml | wc -l) || true
-       not_run=$(xmllint --xpath "//return/status[@status='NOT RUN']" ./output.xml | wc -l) || true
-       total=$((passed + failed + not_run))
-       echo "### Sanity Test Summary" >> $GITHUB_STEP_SUMMARY
-       echo "- Total: $total" >> $GITHUB_STEP_SUMMARY
-       echo "- ✅ Passed: $passed" >> $GITHUB_STEP_SUMMARY
-       echo "- ❌ Failed: $failed" >> $GITHUB_STEP_SUMMARY
-       echo "- ⏭️ Not Run: $not_run" >> $GITHUB_STEP_SUMMARY
-       echo "- 📄 [Full Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
     - name: Install kubectl
       uses: azure/setup-kubectl@v4
       with:
@@ -102,18 +66,46 @@ jobs:
       run: |
         kubectl get nodes
         kubectl cluster-info
-        
+    - name: Log in to GitHub Container Registry
+      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #3.4.0
+      with:
+        registry: ghcr.io
+        username: ${{ github.actor }}
+        password: ${{ secrets.GITHUB_TOKEN }}
+    - name: Sanity Test 
+      run: | 
+       sudo apt-get update
+       sudo pip install robotframework
+       lspci | grep -i vga
+       sudo apt install -y python3-nose libxml2-utils vlc
+       cd edge-ai-suites-repo/manufacturing-ai-suite/industrial-edge-insights-vision/tests/robot_files
+       robot test.robot || true  &
+       sleep 480
+       docker logs dlstreamer-pipeline-server >> dlsps_logs.txt &
+       wait
+       mkdir -p /tmp/test_results
+       cp -r report.html log.html output.xml dlsps_logs.txt /tmp/test_results/
+       passed=$(xmllint --xpath "//return/status[@status='PASS']" ./output.xml | wc -l) || true
+       failed=$(xmllint --xpath "//return/status[@status='FAIL']" ./output.xml | wc -l) || true
+       not_run=$(xmllint --xpath "//return/status[@status='NOT RUN']" ./output.xml | wc -l) || true
+       total=$((passed + failed + not_run))
+       echo "### Sanity Test Summary" >> $GITHUB_STEP_SUMMARY
+       echo "- Total: $total" >> $GITHUB_STEP_SUMMARY
+       echo "- ✅ Passed: $passed" >> $GITHUB_STEP_SUMMARY
+       echo "- ❌ Failed: $failed" >> $GITHUB_STEP_SUMMARY
+       echo "- ⏭️ Not Run: $not_run" >> $GITHUB_STEP_SUMMARY
+       echo "- 📄 [Full Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
     - name: Helm Sanity Test 
-      run: |  
-       python3 -m venv venv
-       source venv/bin/activate
-       pip install --upgrade pip
-       pip install robotframework selenium
+      run: | 
+       sudo apt-get update
+       sudo pip install robotframework
+       lspci | grep -i vga
+       sudo apt install -y python3-nose libxml2-utils vlc
        cd edge-ai-suites-repo/manufacturing-ai-suite/industrial-edge-insights-vision/tests/robot_files
        robot test_helm.robot || true  &
        sleep 480
-      
-       
+       docker logs dlstreamer-pipeline-server >> dlsps_logs.txt &
+       wait
        mkdir -p /tmp/test_results
        cp -r report.html log.html output.xml dlsps_logs.txt /tmp/test_results/
        passed=$(xmllint --xpath "//return/status[@status='PASS']" ./output.xml | wc -l) || true
@@ -139,6 +131,3 @@ jobs:
                docker rmi -f $(docker images -aq) || true
         fi
         sudo rm -rf /tmp/test_results/*
-
-
-
